//
// Created by albert on 3/12/18.
//

#include "native-backend/server/TcpConnection.h"

/*!\brief Starts reading the request header asynchronously and calls TcpConnection::onRequestRead when done.
 * Called from Server::handle_accept when a client connects.
 * Expects connection to be present.*/
void native_backend::TcpConnection::start() {
    boost::asio::async_read_until(socket_, this->request_buffer_, "\r\n\r\n",
                                  boost::bind(&TcpConnection::onRequestRead, this,
                                              boost::asio::placeholders::error,
                                              boost::asio::placeholders::bytes_transferred));
}

/*!\brief Creates a shared_ptr of TcpConnection and stores a copy of it in the created instance.
 * The copy is created to make sure that the shared_ptr isn't destroyed before asynchronous handling
 * of the request has finished.*/
native_backend::TcpConnection::shared_ptr_t native_backend::TcpConnection::create(boost::asio::io_context &io_context) {
    shared_ptr_t myPtr = shared_ptr_t(new TcpConnection(io_context));
    myPtr->setRef(myPtr);
    return myPtr;
}

/*!\brief Sets \c TcpConnection::shared_ptr_to_this_*/
void native_backend::TcpConnection::setRef(native_backend::TcpConnection::shared_ptr_t shared_ptr_to_this) {
    this->shared_ptr_to_this_ = shared_ptr_to_this;
}

/*\brief Return \c TcpConnection::socket_*/
tcp::socket &native_backend::TcpConnection::getSocket() {
    return this->socket_;
}

native_backend::TcpConnection::TcpConnection(boost::asio::io_context &io_context)
        : socket_(io_context) {}

/*!\brief Resets \c shared_ptr_to_this_ so it can be freed.
 * Called after the response has been sent to the client.*/
void native_backend::TcpConnection::onResponded(const boost::system::error_code &, size_t) {
    shared_ptr_to_this_.reset();
}

/*!\brief Sends back the HTML code generated by the controllers.
 * Called after the request has been read asynchronously.
 * Binds TcpConnection::onResponded for when the response has been written.*/
void native_backend::TcpConnection::onRequestRead(const boost::system::error_code &, size_t) {
    std::string request((std::istreambuf_iterator<char>(&this->request_buffer_)),
                  std::istreambuf_iterator<char>());

    /*TODO: Get routes from routing*/
    /*TODO: Get HTML from controllers*/
    std::string html = "<html><body><p>" + request + "</p></body></html>";

    std::string message = "HTTP/1.1 200 OK\n"
                                  "Content-length: " + std::to_string(html.size()) + "\n"
                                  "Content-Type: text/html\n\n" +
                          html + "\n";


    boost::asio::async_write(socket_, boost::asio::buffer(message),
                             boost::bind(&TcpConnection::onResponded, shared_from_this(),
                                         boost::asio::placeholders::error,
                                         boost::asio::placeholders::bytes_transferred));

}
